name: moviedb
description: A flutter project mainly for education.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.4
  logger: ^1.1.0
  smooth_star_rating: ^1.1.1
  url_launcher: ^6.1.5
  package_info_plus: ^1.4.2
  custom_switch: ^0.0.1
  sprintf: ^6.0.0
  flutter_launcher_icons: ^0.9.3
  shared_preferences: ^2.0.15
  qr_code_scanner: ^0.7.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.5.3
  google_maps_flutter: ^2.1.10
  geolocator: ^9.0.1
  flutter_polyline_points: ^1.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  bloc_concurrency: ^0.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/ic_launcher.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: 'roboto'
      fonts:
        - asset: 'assets/fonts/Roboto-Thin.ttf'
          weight: 100
        - asset: 'assets/fonts/Roboto-ThinItalic.ttf'
          weight: 100
          style: italic
        - asset: 'assets/fonts/Roboto-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Roboto-Bold.ttf'
          weight: 700
    - family: 'stick'
      fonts:
        - asset: 'assets/fonts/Stick-Regular.ttf'
          weight: 400
    - family: 'montserrat'
      fonts:
        - asset: 'assets/fonts/Montserrat-ExtraLight.ttf'
        - asset: 'assets/fonts/Montserrat-Regular.ttf'
