name: movie_db
description: A new Flutter application.
publish_to: 'none'
version: 0.0.2+2
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  http: ^0.12.2
  logger: ^0.9.4
  cupertino_icons: ^1.0.0
  smooth_star_rating: ^1.1.1
  url_launcher: ^5.7.10
  package_info: ^0.4.0+16
  custom_switch: ^0.0.1
  sprintf: ^4.0.0
  flutter_launcher_icons: ^0.8.1
  shared_preferences: ^0.5.12+4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/ic_launcher.png"
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: 'roboto'
      fonts:
        - asset: 'assets/fonts/Roboto-Thin.ttf'
          weight: 100
        - asset: 'assets/fonts/Roboto-ThinItalic.ttf'
          weight: 100
          style: italic
        - asset: 'assets/fonts/Roboto-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Roboto-Bold.ttf'
          weight: 700
    - family: 'stick'
      fonts:
        - asset: 'assets/fonts/Stick-Regular.ttf'
          weight: 400
    - family: 'montserrat'
      fonts:
        - asset: 'assets/fonts/Montserrat-ExtraLight.ttf'
        - asset: 'assets/fonts/Montserrat-Regular.ttf'