name: movie_db
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  logger: ^0.9.4
  cupertino_icons: ^1.0.0
  smooth_star_rating: ^1.1.1
  url_launcher: ^5.7.10
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/